#Stage 1
FROM node as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package*.json .
RUN npm install
COPY . .
ARG REACT_APP_SECRET
ENV REACT_APP_SECRET=$REACT_APP_SECRET
RUN npm run build


#Stage 2
FROM nginx
COPY --from=build /app/build /usr/share/nginx/html

