version: "3.9"
services:
  api:
    build: 
      context: ./apiExpress
      dockerfile: Dockerfile
    container_name: api
    hostname: api
    restart: always
    ports: 
      - "4000:4000"
    volumes:
      - './apiExpress:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=development
    networks:
      - iab330
  client:
    build: 
      context: ./client/client-react
      dockerfile: Dockerfile.dev
    container_name: client_dev
    hostname: client_dev
    restart: always
    ports: 
      - "3000:3000"
    volumes:
      - './client/src:/app/src'
      - '/app/node_modules'
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    networks:
      - iab330
networks:
  iab330:
    external: true
